version: '3'

services:
  web:
    build: ./website
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - website:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.prod
volumes:
  website:
  postgres_data: