# Generated by Django 3.0.3 on 2020-05-31 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20200301_1755"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="post",
            name="tagline",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
