# Generated by Django 3.0.7 on 2020-06-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_auto_20200611_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="blog.Post",
            ),
        ),
    ]
