# Generated by Django 3.0.7 on 2020-07-24 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_auto_20200611_1336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="subbed",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
