# Generated by Django 3.0.7 on 2020-07-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200724_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='subbed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
