# Generated by Django 3.0.7 on 2020-07-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_auto_20200726_2000"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post", options={"ordering": ["-posted__year", "-posted__month"]},
        ),
    ]
