# Generated by Django 3.0.7 on 2020-07-27 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200726_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='background',
            field=models.CharField(db_index=True, max_length=7, validators=[django.core.validators.RegexValidator('^[#][a-zA-Z0-9]{3,6}$', 'Only a Hex formatted string is allowed.')]),
        ),
    ]
